# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title EM Algorithm for Repeated Experiment (Rcpp Version)
#' @description Inference on repeated experiment using EM algorithm (Rcpp version).
#' @param data the data frame to be analyzed
#' @return a list containing the estimation results, iteration times and optimal log likelihood.
#' @examples
#' \dontrun{
#' data(reaction_time)
#' attach(reaction_time)
#' result <- emforreC(reaction_time)
#' alpha.hat <- result$alpha; lambda.hat <- result$lambda
#' beta.hat <- result$beta; mu.hat <- result$mu; gamma.hat <- result$gamma
#' sigma.hat <- result$sigma; tau.hat <- result$tau
#' }
#' @export
emforreC <- function(data) {
    .Call('_StatComp22034_emforreC', PACKAGE = 'StatComp22034', data)
}

